name       : powerlevel9k
version    : 0.6.7
release    : 3
source     :
    - https://github.com/bhilburn/powerlevel9k/archive/v0.6.7.tar.gz : d6e3eaee522a70aa03aa832787e1526aba6419f6347d3e5058137e18cfadb13d
license    : MIT
component  : system.utils
summary    : Powerlevel9k theme for zsh
description: |
    Powerlevel9k is a theme for ZSH which uses Powerline Fonts. It can be used with vanilla ZSH or ZSH frameworks such as Oh-My-Zsh, Prezto, Antigen, and many others.
rundeps    :
    - powerline-fonts
    - zsh
install    : |
    install -D -m644 powerlevel9k.zsh-theme "$installdir/usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme"
    for FILE in functions/*.zsh; do
      install -D -m644 "${FILE}" "$installdir/usr/share/zsh-theme-powerlevel9k/functions/$(basename ${FILE})"
    done
    install -D -m644 LICENSE "$installdir/usr/share/doc/powerlevel9k/LICENSE"
    install -D -m644 README.md "$installdir/usr/share/doc/powerlevel9k/README.md"

