name       : powerlevel9k
version    : 0.6.5
release    : 1
source     :
    -  https://github.com/bhilburn/powerlevel9k/archive/v0.6.5.tar.gz : d69d291618fd506e5889240d23080eb40c3f02493682d117880d69e3f71e349c
license    : MIT
component  : system.utils
summary    : Powerlevel9k theme for zsh
description: |
    Powerlevel9k is a theme for ZSH which uses Powerline Fonts. It can be used with vanilla ZSH or ZSH frameworks such as Oh-My-Zsh, Prezto, Antigen, and many others.
rundeps    :
    - powerline-fonts
    - zsh
install    : |
    install -D -m644 powerlevel9k.zsh-theme "$installdir/usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme"
    for FILE in functions/*.zsh; do
      install -D -m644 "${FILE}" "$installdir/usr/share/zsh-theme-powerlevel9k/functions/$(basename ${FILE})"
    done
    install -D -m644 LICENSE "$installdir/usr/share/doc/powerlevel9k/LICENSE"
    install -D -m644 README.md "$installdir/usr/share/doc/powerlevel9k/README.md"

